{
 "title": "Meet.vpsFree.cz Status",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Conferences now",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jitsi_conferences{project=\"vpsfree\"})"
    }
   ]
  },
  {
   "title": "Participants now",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jitsi_participants{project=\"vpsfree\"})"
    }
   ]
  },
  {
   "title": "Largest conference now",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(jitsi_largest_conference{project=\"vpsfree\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by(alias) (1-irate(node_cpu{mode=\"idle\",alias=\"meet-jvb1\",project=\"vpsfree\"}[5m]))",
     "legendFormat": "jvb1"
    },
    {
     "expr": "avg by(alias) (1-irate(node_cpu{mode=\"idle\",alias=\"meet-jvb2\",project=\"vpsfree\"}[5m]))",
     "legendFormat": "jvb2"
    },
    {
     "expr": "avg by(alias) (1-irate(node_cpu{mode=\"idle\",alias=\"meet-jvb3\",project=\"vpsfree\"}[5m]))",
     "legendFormat": "jvb3"
    },
    {
     "expr": "avg by(alias) (1-irate(node_cpu{mode=\"idle\",alias=\"meet-jvb4\",project=\"vpsfree\"}[5m]))",
     "legendFormat": "jvb4"
    },
    {
     "expr": "avg by(alias) (1-irate(node_cpu{mode=\"idle\",alias=\"meet-jvb5\",project=\"vpsfree\"}[5m]))",
     "legendFormat": "jvb5"
    },
    {
     "expr": "avg by(alias) (1-irate(node_cpu{mode=\"idle\",alias=\"meet-jvb6\",project=\"vpsfree\"}[5m]))",
     "legendFormat": "jvb6"
    },
    {
     "expr": "avg by(alias) (1-irate(node_cpu{mode=\"idle\",alias=\"meet-jvb7\",project=\"vpsfree\"}[5m]))",
     "legendFormat": "jvb7"
    },
    {
     "expr": "avg by(alias) (1-irate(node_cpu{mode=\"idle\",alias=\"meet-jvb8\",project=\"vpsfree\"}[5m]))",
     "legendFormat": "jvb8"
    },
    {
     "expr": "avg by(alias) (1-irate(node_cpu{mode=\"idle\",alias=\"meet-jvb9\",project=\"vpsfree\"}[5m]))",
     "legendFormat": "jvb9"
    },
    {
     "expr": "avg by(alias) (1-irate(node_cpu{mode=\"idle\",alias=\"meet-jvb10\",project=\"vpsfree\"}[5m]))",
     "legendFormat": "jvb10"
    },
    {
     "expr": "avg by(alias) (1-irate(node_cpu{mode=\"idle\",alias=\"meet-jvb11\",project=\"vpsfree\"}[5m]))",
     "legendFormat": "jvb11"
    },
    {
     "expr": "avg by(alias) (1-irate(node_cpu{mode=\"idle\",alias=\"meet-jvb12\",project=\"vpsfree\"}[5m]))",
     "legendFormat": "jvb12"
    },
    {
     "expr": "avg by(alias) (1-irate(node_cpu{mode=\"idle\",alias=\"meet-jvb13\",project=\"vpsfree\"}[5m]))",
     "legendFormat": "jvb13"
    },
    {
     "expr": "avg by(alias) (1-irate(node_cpu{mode=\"idle\",alias=\"meet-jvb14\",project=\"vpsfree\"}[5m]))",
     "legendFormat": "jvb14"
    },
    {
     "expr": "avg by(alias) (1-irate(node_cpu{mode=\"idle\",alias=\"meet-jvb15\",project=\"vpsfree\"}[5m]))",
     "legendFormat": "jvb15"
    },
    {
     "expr": "avg by(alias) (1-irate(node_cpu{mode=\"idle\",alias=\"meet-jvb16\",project=\"vpsfree\"}[5m]))",
     "legendFormat": "jvb16"
    },
    {
     "expr": "avg by(alias) (1-irate(node_cpu{mode=\"idle\",alias=\"meet-jvb17\",project=\"vpsfree\"}[5m]))",
     "legendFormat": "jvb17"
    },
    {
     "expr": "avg by(alias) (1-irate(node_cpu{mode=\"idle\",alias=\"meet-jvb18\",project=\"vpsfree\"}[5m]))",
     "legendFormat": "jvb18"
    },
    {
     "expr": "avg by(alias) (1-irate(node_cpu{mode=\"idle\",alias=\"meet-jvb19\",project=\"vpsfree\"}[5m]))",
     "legendFormat": "jvb19"
    },
    {
     "expr": "avg by(alias) (1-irate(node_cpu{mode=\"idle\",alias=\"meet-jvb20\",project=\"vpsfree\"}[5m]))",
     "legendFormat": "jvb20"
    }
   ]
  },
  {
   "title": "Round Trip Loss",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "jitsi_rtp_loss{alias=\"meet-jvb1\",project=\"vpsfree\"}",
     "legendFormat": "jvb1"
    },
    {
     "expr": "jitsi_rtp_loss{alias=\"meet-jvb2\",project=\"vpsfree\"}",
     "legendFormat": "jvb2"
    },
    {
     "expr": "jitsi_rtp_loss{alias=\"meet-jvb3\",project=\"vpsfree\"}",
     "legendFormat": "jvb3"
    },
    {
     "expr": "jitsi_rtp_loss{alias=\"meet-jvb4\",project=\"vpsfree\"}",
     "legendFormat": "jvb4"
    },
    {
     "expr": "jitsi_rtp_loss{alias=\"meet-jvb5\",project=\"vpsfree\"}",
     "legendFormat": "jvb5"
    },
    {
     "expr": "jitsi_rtp_loss{alias=\"meet-jvb6\",project=\"vpsfree\"}",
     "legendFormat": "jvb6"
    },
    {
     "expr": "jitsi_rtp_loss{alias=\"meet-jvb7\",project=\"vpsfree\"}",
     "legendFormat": "jvb7"
    },
    {
     "expr": "jitsi_rtp_loss{alias=\"meet-jvb8\",project=\"vpsfree\"}",
     "legendFormat": "jvb8"
    },
    {
     "expr": "jitsi_rtp_loss{alias=\"meet-jvb9\",project=\"vpsfree\"}",
     "legendFormat": "jvb9"
    },
    {
     "expr": "jitsi_rtp_loss{alias=\"meet-jvb10\",project=\"vpsfree\"}",
     "legendFormat": "jvb10"
    },
    {
     "expr": "jitsi_rtp_loss{alias=\"meet-jvb11\",project=\"vpsfree\"}",
     "legendFormat": "jvb11"
    },
    {
     "expr": "jitsi_rtp_loss{alias=\"meet-jvb12\",project=\"vpsfree\"}",
     "legendFormat": "jvb12"
    },
    {
     "expr": "jitsi_rtp_loss{alias=\"meet-jvb13\",project=\"vpsfree\"}",
     "legendFormat": "jvb13"
    },
    {
     "expr": "jitsi_rtp_loss{alias=\"meet-jvb14\",project=\"vpsfree\"}",
     "legendFormat": "jvb14"
    },
    {
     "expr": "jitsi_rtp_loss{alias=\"meet-jvb15\",project=\"vpsfree\"}",
     "legendFormat": "jvb15"
    },
    {
     "expr": "jitsi_rtp_loss{alias=\"meet-jvb16\",project=\"vpsfree\"}",
     "legendFormat": "jvb16"
    },
    {
     "expr": "jitsi_rtp_loss{alias=\"meet-jvb17\",project=\"vpsfree\"}",
     "legendFormat": "jvb17"
    },
    {
     "expr": "jitsi_rtp_loss{alias=\"meet-jvb18\",project=\"vpsfree\"}",
     "legendFormat": "jvb18"
    },
    {
     "expr": "jitsi_rtp_loss{alias=\"meet-jvb19\",project=\"vpsfree\"}",
     "legendFormat": "jvb19"
    },
    {
     "expr": "jitsi_rtp_loss{alias=\"meet-jvb20\",project=\"vpsfree\"}",
     "legendFormat": "jvb20"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (avg by (alias) (1-irate(node_cpu{mode=\"idle\",job=\"meet-jvbs\",project=\"vpsfree\"}[5m])))"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jitsi_bit_rate_download{project=\"vpsfree\"})"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jitsi_bit_rate_upload{project=\"vpsfree\"})"
    }
   ]
  },
  {
   "title": "Loss Rate Download",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "jitsi_loss_rate_download{alias=\"meet-jvb1\",project=\"vpsfree\"}",
     "legendFormat": "jvb1"
    },
    {
     "expr": "jitsi_loss_rate_download{alias=\"meet-jvb2\",project=\"vpsfree\"}",
     "legendFormat": "jvb2"
    },
    {
     "expr": "jitsi_loss_rate_download{alias=\"meet-jvb3\",project=\"vpsfree\"}",
     "legendFormat": "jvb3"
    },
    {
     "expr": "jitsi_loss_rate_download{alias=\"meet-jvb4\",project=\"vpsfree\"}",
     "legendFormat": "jvb4"
    },
    {
     "expr": "jitsi_loss_rate_download{alias=\"meet-jvb5\",project=\"vpsfree\"}",
     "legendFormat": "jvb5"
    },
    {
     "expr": "jitsi_loss_rate_download{alias=\"meet-jvb6\",project=\"vpsfree\"}",
     "legendFormat": "jvb6"
    },
    {
     "expr": "jitsi_loss_rate_download{alias=\"meet-jvb7\",project=\"vpsfree\"}",
     "legendFormat": "jvb7"
    },
    {
     "expr": "jitsi_loss_rate_download{alias=\"meet-jvb8\",project=\"vpsfree\"}",
     "legendFormat": "jvb8"
    },
    {
     "expr": "jitsi_loss_rate_download{alias=\"meet-jvb9\",project=\"vpsfree\"}",
     "legendFormat": "jvb9"
    },
    {
     "expr": "jitsi_loss_rate_download{alias=\"meet-jvb10\",project=\"vpsfree\"}",
     "legendFormat": "jvb10"
    },
    {
     "expr": "jitsi_loss_rate_download{alias=\"meet-jvb11\",project=\"vpsfree\"}",
     "legendFormat": "jvb11"
    },
    {
     "expr": "jitsi_loss_rate_download{alias=\"meet-jvb12\",project=\"vpsfree\"}",
     "legendFormat": "jvb12"
    },
    {
     "expr": "jitsi_loss_rate_download{alias=\"meet-jvb13\",project=\"vpsfree\"}",
     "legendFormat": "jvb13"
    },
    {
     "expr": "jitsi_loss_rate_download{alias=\"meet-jvb14\",project=\"vpsfree\"}",
     "legendFormat": "jvb14"
    },
    {
     "expr": "jitsi_loss_rate_download{alias=\"meet-jvb15\",project=\"vpsfree\"}",
     "legendFormat": "jvb15"
    },
    {
     "expr": "jitsi_loss_rate_download{alias=\"meet-jvb16\",project=\"vpsfree\"}",
     "legendFormat": "jvb16"
    },
    {
     "expr": "jitsi_loss_rate_download{alias=\"meet-jvb17\",project=\"vpsfree\"}",
     "legendFormat": "jvb17"
    },
    {
     "expr": "jitsi_loss_rate_download{alias=\"meet-jvb18\",project=\"vpsfree\"}",
     "legendFormat": "jvb18"
    },
    {
     "expr": "jitsi_loss_rate_download{alias=\"meet-jvb19\",project=\"vpsfree\"}",
     "legendFormat": "jvb19"
    },
    {
     "expr": "jitsi_loss_rate_download{alias=\"meet-jvb20\",project=\"vpsfree\"}",
     "legendFormat": "jvb20"
    }
   ]
  },
  {
   "title": "Loss Rate Upload",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "jitsi_loss_rate_upload{alias=\"meet-jvb1\",project=\"vpsfree\"}",
     "legendFormat": "jvb1"
    },
    {
     "expr": "jitsi_loss_rate_upload{alias=\"meet-jvb2\",project=\"vpsfree\"}",
     "legendFormat": "jvb2"
    },
    {
     "expr": "jitsi_loss_rate_upload{alias=\"meet-jvb3\",project=\"vpsfree\"}",
     "legendFormat": "jvb3"
    },
    {
     "expr": "jitsi_loss_rate_upload{alias=\"meet-jvb4\",project=\"vpsfree\"}",
     "legendFormat": "jvb4"
    },
    {
     "expr": "jitsi_loss_rate_upload{alias=\"meet-jvb5\",project=\"vpsfree\"}",
     "legendFormat": "jvb5"
    },
    {
     "expr": "jitsi_loss_rate_upload{alias=\"meet-jvb6\",project=\"vpsfree\"}",
     "legendFormat": "jvb6"
    },
    {
     "expr": "jitsi_loss_rate_upload{alias=\"meet-jvb7\",project=\"vpsfree\"}",
     "legendFormat": "jvb7"
    },
    {
     "expr": "jitsi_loss_rate_upload{alias=\"meet-jvb8\",project=\"vpsfree\"}",
     "legendFormat": "jvb8"
    },
    {
     "expr": "jitsi_loss_rate_upload{alias=\"meet-jvb9\",project=\"vpsfree\"}",
     "legendFormat": "jvb9"
    },
    {
     "expr": "jitsi_loss_rate_upload{alias=\"meet-jvb10\",project=\"vpsfree\"}",
     "legendFormat": "jvb10"
    },
    {
     "expr": "jitsi_loss_rate_upload{alias=\"meet-jvb11\",project=\"vpsfree\"}",
     "legendFormat": "jvb11"
    },
    {
     "expr": "jitsi_loss_rate_upload{alias=\"meet-jvb12\",project=\"vpsfree\"}",
     "legendFormat": "jvb12"
    },
    {
     "expr": "jitsi_loss_rate_upload{alias=\"meet-jvb13\",project=\"vpsfree\"}",
     "legendFormat": "jvb13"
    },
    {
     "expr": "jitsi_loss_rate_upload{alias=\"meet-jvb14\",project=\"vpsfree\"}",
     "legendFormat": "jvb14"
    },
    {
     "expr": "jitsi_loss_rate_upload{alias=\"meet-jvb15\",project=\"vpsfree\"}",
     "legendFormat": "jvb15"
    },
    {
     "expr": "jitsi_loss_rate_upload{alias=\"meet-jvb16\",project=\"vpsfree\"}",
     "legendFormat": "jvb16"
    },
    {
     "expr": "jitsi_loss_rate_upload{alias=\"meet-jvb17\",project=\"vpsfree\"}",
     "legendFormat": "jvb17"
    },
    {
     "expr": "jitsi_loss_rate_upload{alias=\"meet-jvb18\",project=\"vpsfree\"}",
     "legendFormat": "jvb18"
    },
    {
     "expr": "jitsi_loss_rate_upload{alias=\"meet-jvb19\",project=\"vpsfree\"}",
     "legendFormat": "jvb19"
    },
    {
     "expr": "jitsi_loss_rate_upload{alias=\"meet-jvb20\",project=\"vpsfree\"}",
     "legendFormat": "jvb20"
    }
   ]
  },
  {
   "title": "Running Conferences",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jitsi_conferences{alias=\"meet-jvb1\",project=\"vpsfree\"}",
     "legendFormat": "jvb1"
    },
    {
     "expr": "jitsi_conferences{alias=\"meet-jvb2\",project=\"vpsfree\"}",
     "legendFormat": "jvb2"
    },
    {
     "expr": "jitsi_conferences{alias=\"meet-jvb3\",project=\"vpsfree\"}",
     "legendFormat": "jvb3"
    },
    {
     "expr": "jitsi_conferences{alias=\"meet-jvb4\",project=\"vpsfree\"}",
     "legendFormat": "jvb4"
    },
    {
     "expr": "jitsi_conferences{alias=\"meet-jvb5\",project=\"vpsfree\"}",
     "legendFormat": "jvb5"
    },
    {
     "expr": "jitsi_conferences{alias=\"meet-jvb6\",project=\"vpsfree\"}",
     "legendFormat": "jvb6"
    },
    {
     "expr": "jitsi_conferences{alias=\"meet-jvb7\",project=\"vpsfree\"}",
     "legendFormat": "jvb7"
    },
    {
     "expr": "jitsi_conferences{alias=\"meet-jvb8\",project=\"vpsfree\"}",
     "legendFormat": "jvb8"
    },
    {
     "expr": "jitsi_conferences{alias=\"meet-jvb9\",project=\"vpsfree\"}",
     "legendFormat": "jvb9"
    },
    {
     "expr": "jitsi_conferences{alias=\"meet-jvb10\",project=\"vpsfree\"}",
     "legendFormat": "jvb10"
    },
    {
     "expr": "jitsi_conferences{alias=\"meet-jvb11\",project=\"vpsfree\"}",
     "legendFormat": "jvb11"
    },
    {
     "expr": "jitsi_conferences{alias=\"meet-jvb12\",project=\"vpsfree\"}",
     "legendFormat": "jvb12"
    },
    {
     "expr": "jitsi_conferences{alias=\"meet-jvb13\",project=\"vpsfree\"}",
     "legendFormat": "jvb13"
    },
    {
     "expr": "jitsi_conferences{alias=\"meet-jvb14\",project=\"vpsfree\"}",
     "legendFormat": "jvb14"
    },
    {
     "expr": "jitsi_conferences{alias=\"meet-jvb15\",project=\"vpsfree\"}",
     "legendFormat": "jvb15"
    },
    {
     "expr": "jitsi_conferences{alias=\"meet-jvb16\",project=\"vpsfree\"}",
     "legendFormat": "jvb16"
    },
    {
     "expr": "jitsi_conferences{alias=\"meet-jvb17\",project=\"vpsfree\"}",
     "legendFormat": "jvb17"
    },
    {
     "expr": "jitsi_conferences{alias=\"meet-jvb18\",project=\"vpsfree\"}",
     "legendFormat": "jvb18"
    },
    {
     "expr": "jitsi_conferences{alias=\"meet-jvb19\",project=\"vpsfree\"}",
     "legendFormat": "jvb19"
    },
    {
     "expr": "jitsi_conferences{alias=\"meet-jvb20\",project=\"vpsfree\"}",
     "legendFormat": "jvb20"
    }
   ]
  },
  {
   "title": "Video Channels",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jitsi_videochannels{alias=\"meet-jvb1\",project=\"vpsfree\"}",
     "legendFormat": "jvb1"
    },
    {
     "expr": "jitsi_videochannels{alias=\"meet-jvb2\",project=\"vpsfree\"}",
     "legendFormat": "jvb2"
    },
    {
     "expr": "jitsi_videochannels{alias=\"meet-jvb3\",project=\"vpsfree\"}",
     "legendFormat": "jvb3"
    },
    {
     "expr": "jitsi_videochannels{alias=\"meet-jvb4\",project=\"vpsfree\"}",
     "legendFormat": "jvb4"
    },
    {
     "expr": "jitsi_videochannels{alias=\"meet-jvb5\",project=\"vpsfree\"}",
     "legendFormat": "jvb5"
    },
    {
     "expr": "jitsi_videochannels{alias=\"meet-jvb6\",project=\"vpsfree\"}",
     "legendFormat": "jvb6"
    },
    {
     "expr": "jitsi_videochannels{alias=\"meet-jvb7\",project=\"vpsfree\"}",
     "legendFormat": "jvb7"
    },
    {
     "expr": "jitsi_videochannels{alias=\"meet-jvb8\",project=\"vpsfree\"}",
     "legendFormat": "jvb8"
    },
    {
     "expr": "jitsi_videochannels{alias=\"meet-jvb9\",project=\"vpsfree\"}",
     "legendFormat": "jvb9"
    },
    {
     "expr": "jitsi_videochannels{alias=\"meet-jvb10\",project=\"vpsfree\"}",
     "legendFormat": "jvb10"
    },
    {
     "expr": "jitsi_videochannels{alias=\"meet-jvb11\",project=\"vpsfree\"}",
     "legendFormat": "jvb11"
    },
    {
     "expr": "jitsi_videochannels{alias=\"meet-jvb12\",project=\"vpsfree\"}",
     "legendFormat": "jvb12"
    },
    {
     "expr": "jitsi_videochannels{alias=\"meet-jvb13\",project=\"vpsfree\"}",
     "legendFormat": "jvb13"
    },
    {
     "expr": "jitsi_videochannels{alias=\"meet-jvb14\",project=\"vpsfree\"}",
     "legendFormat": "jvb14"
    },
    {
     "expr": "jitsi_videochannels{alias=\"meet-jvb15\",project=\"vpsfree\"}",
     "legendFormat": "jvb15"
    },
    {
     "expr": "jitsi_videochannels{alias=\"meet-jvb16\",project=\"vpsfree\"}",
     "legendFormat": "jvb16"
    },
    {
     "expr": "jitsi_videochannels{alias=\"meet-jvb17\",project=\"vpsfree\"}",
     "legendFormat": "jvb17"
    },
    {
     "expr": "jitsi_videochannels{alias=\"meet-jvb18\",project=\"vpsfree\"}",
     "legendFormat": "jvb18"
    },
    {
     "expr": "jitsi_videochannels{alias=\"meet-jvb19\",project=\"vpsfree\"}",
     "legendFormat": "jvb19"
    },
    {
     "expr": "jitsi_videochannels{alias=\"meet-jvb20\",project=\"vpsfree\"}",
     "legendFormat": "jvb20"
    }
   ]
  },
  {
   "title": "Aggregate Jitter",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "jitsi_jitter_aggregate{alias=\"meet-jvb1\",project=\"vpsfree\"}",
     "legendFormat": "jvb1"
    },
    {
     "expr": "jitsi_jitter_aggregate{alias=\"meet-jvb2\",project=\"vpsfree\"}",
     "legendFormat": "jvb2"
    },
    {
     "expr": "jitsi_jitter_aggregate{alias=\"meet-jvb3\",project=\"vpsfree\"}",
     "legendFormat": "jvb3"
    },
    {
     "expr": "jitsi_jitter_aggregate{alias=\"meet-jvb4\",project=\"vpsfree\"}",
     "legendFormat": "jvb4"
    },
    {
     "expr": "jitsi_jitter_aggregate{alias=\"meet-jvb5\",project=\"vpsfree\"}",
     "legendFormat": "jvb5"
    },
    {
     "expr": "jitsi_jitter_aggregate{alias=\"meet-jvb6\",project=\"vpsfree\"}",
     "legendFormat": "jvb6"
    },
    {
     "expr": "jitsi_jitter_aggregate{alias=\"meet-jvb7\",project=\"vpsfree\"}",
     "legendFormat": "jvb7"
    },
    {
     "expr": "jitsi_jitter_aggregate{alias=\"meet-jvb8\",project=\"vpsfree\"}",
     "legendFormat": "jvb8"
    },
    {
     "expr": "jitsi_jitter_aggregate{alias=\"meet-jvb9\",project=\"vpsfree\"}",
     "legendFormat": "jvb9"
    },
    {
     "expr": "jitsi_jitter_aggregate{alias=\"meet-jvb10\",project=\"vpsfree\"}",
     "legendFormat": "jvb10"
    },
    {
     "expr": "jitsi_jitter_aggregate{alias=\"meet-jvb11\",project=\"vpsfree\"}",
     "legendFormat": "jvb11"
    },
    {
     "expr": "jitsi_jitter_aggregate{alias=\"meet-jvb12\",project=\"vpsfree\"}",
     "legendFormat": "jvb12"
    },
    {
     "expr": "jitsi_jitter_aggregate{alias=\"meet-jvb13\",project=\"vpsfree\"}",
     "legendFormat": "jvb13"
    },
    {
     "expr": "jitsi_jitter_aggregate{alias=\"meet-jvb14\",project=\"vpsfree\"}",
     "legendFormat": "jvb14"
    },
    {
     "expr": "jitsi_jitter_aggregate{alias=\"meet-jvb15\",project=\"vpsfree\"}",
     "legendFormat": "jvb15"
    },
    {
     "expr": "jitsi_jitter_aggregate{alias=\"meet-jvb16\",project=\"vpsfree\"}",
     "legendFormat": "jvb16"
    },
    {
     "expr": "jitsi_jitter_aggregate{alias=\"meet-jvb17\",project=\"vpsfree\"}",
     "legendFormat": "jvb17"
    },
    {
     "expr": "jitsi_jitter_aggregate{alias=\"meet-jvb18\",project=\"vpsfree\"}",
     "legendFormat": "jvb18"
    },
    {
     "expr": "jitsi_jitter_aggregate{alias=\"meet-jvb19\",project=\"vpsfree\"}",
     "legendFormat": "jvb19"
    },
    {
     "expr": "jitsi_jitter_aggregate{alias=\"meet-jvb20\",project=\"vpsfree\"}",
     "legendFormat": "jvb20"
    }
   ]
  },
  {
   "title": "Aggregate Round Trip Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "jitsi_rtt_aggregate{alias=\"meet-jvb1\",project=\"vpsfree\"}",
     "legendFormat": "jvb1"
    },
    {
     "expr": "jitsi_rtt_aggregate{alias=\"meet-jvb2\",project=\"vpsfree\"}",
     "legendFormat": "jvb2"
    },
    {
     "expr": "jitsi_rtt_aggregate{alias=\"meet-jvb3\",project=\"vpsfree\"}",
     "legendFormat": "jvb3"
    },
    {
     "expr": "jitsi_rtt_aggregate{alias=\"meet-jvb4\",project=\"vpsfree\"}",
     "legendFormat": "jvb4"
    },
    {
     "expr": "jitsi_rtt_aggregate{alias=\"meet-jvb5\",project=\"vpsfree\"}",
     "legendFormat": "jvb5"
    },
    {
     "expr": "jitsi_rtt_aggregate{alias=\"meet-jvb6\",project=\"vpsfree\"}",
     "legendFormat": "jvb6"
    },
    {
     "expr": "jitsi_rtt_aggregate{alias=\"meet-jvb7\",project=\"vpsfree\"}",
     "legendFormat": "jvb7"
    },
    {
     "expr": "jitsi_rtt_aggregate{alias=\"meet-jvb8\",project=\"vpsfree\"}",
     "legendFormat": "jvb8"
    },
    {
     "expr": "jitsi_rtt_aggregate{alias=\"meet-jvb9\",project=\"vpsfree\"}",
     "legendFormat": "jvb9"
    },
    {
     "expr": "jitsi_rtt_aggregate{alias=\"meet-jvb10\",project=\"vpsfree\"}",
     "legendFormat": "jvb10"
    },
    {
     "expr": "jitsi_rtt_aggregate{alias=\"meet-jvb11\",project=\"vpsfree\"}",
     "legendFormat": "jvb11"
    },
    {
     "expr": "jitsi_rtt_aggregate{alias=\"meet-jvb12\",project=\"vpsfree\"}",
     "legendFormat": "jvb12"
    },
    {
     "expr": "jitsi_rtt_aggregate{alias=\"meet-jvb13\",project=\"vpsfree\"}",
     "legendFormat": "jvb13"
    },
    {
     "expr": "jitsi_rtt_aggregate{alias=\"meet-jvb14\",project=\"vpsfree\"}",
     "legendFormat": "jvb14"
    },
    {
     "expr": "jitsi_rtt_aggregate{alias=\"meet-jvb15\",project=\"vpsfree\"}",
     "legendFormat": "jvb15"
    },
    {
     "expr": "jitsi_rtt_aggregate{alias=\"meet-jvb16\",project=\"vpsfree\"}",
     "legendFormat": "jvb16"
    },
    {
     "expr": "jitsi_rtt_aggregate{alias=\"meet-jvb17\",project=\"vpsfree\"}",
     "legendFormat": "jvb17"
    },
    {
     "expr": "jitsi_rtt_aggregate{alias=\"meet-jvb18\",project=\"vpsfree\"}",
     "legendFormat": "jvb18"
    },
    {
     "expr": "jitsi_rtt_aggregate{alias=\"meet-jvb19\",project=\"vpsfree\"}",
     "legendFormat": "jvb19"
    },
    {
     "expr": "jitsi_rtt_aggregate{alias=\"meet-jvb20\",project=\"vpsfree\"}",
     "legendFormat": "jvb20"
    }
   ]
  },
  {
   "title": "Connected Participants",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jitsi_participants{alias=\"meet-jvb1\",project=\"vpsfree\"}",
     "legendFormat": "jvb1"
    },
    {
     "expr": "jitsi_participants{alias=\"meet-jvb2\",project=\"vpsfree\"}",
     "legendFormat": "jvb2"
    },
    {
     "expr": "jitsi_participants{alias=\"meet-jvb3\",project=\"vpsfree\"}",
     "legendFormat": "jvb3"
    },
    {
     "expr": "jitsi_participants{alias=\"meet-jvb4\",project=\"vpsfree\"}",
     "legendFormat": "jvb4"
    },
    {
     "expr": "jitsi_participants{alias=\"meet-jvb5\",project=\"vpsfree\"}",
     "legendFormat": "jvb5"
    },
    {
     "expr": "jitsi_participants{alias=\"meet-jvb6\",project=\"vpsfree\"}",
     "legendFormat": "jvb6"
    },
    {
     "expr": "jitsi_participants{alias=\"meet-jvb7\",project=\"vpsfree\"}",
     "legendFormat": "jvb7"
    },
    {
     "expr": "jitsi_participants{alias=\"meet-jvb8\",project=\"vpsfree\"}",
     "legendFormat": "jvb8"
    },
    {
     "expr": "jitsi_participants{alias=\"meet-jvb9\",project=\"vpsfree\"}",
     "legendFormat": "jvb9"
    },
    {
     "expr": "jitsi_participants{alias=\"meet-jvb10\",project=\"vpsfree\"}",
     "legendFormat": "jvb10"
    },
    {
     "expr": "jitsi_participants{alias=\"meet-jvb11\",project=\"vpsfree\"}",
     "legendFormat": "jvb11"
    },
    {
     "expr": "jitsi_participants{alias=\"meet-jvb12\",project=\"vpsfree\"}",
     "legendFormat": "jvb12"
    },
    {
     "expr": "jitsi_participants{alias=\"meet-jvb13\",project=\"vpsfree\"}",
     "legendFormat": "jvb13"
    },
    {
     "expr": "jitsi_participants{alias=\"meet-jvb14\",project=\"vpsfree\"}",
     "legendFormat": "jvb14"
    },
    {
     "expr": "jitsi_participants{alias=\"meet-jvb15\",project=\"vpsfree\"}",
     "legendFormat": "jvb15"
    },
    {
     "expr": "jitsi_participants{alias=\"meet-jvb16\",project=\"vpsfree\"}",
     "legendFormat": "jvb16"
    },
    {
     "expr": "jitsi_participants{alias=\"meet-jvb17\",project=\"vpsfree\"}",
     "legendFormat": "jvb17"
    },
    {
     "expr": "jitsi_participants{alias=\"meet-jvb18\",project=\"vpsfree\"}",
     "legendFormat": "jvb18"
    },
    {
     "expr": "jitsi_participants{alias=\"meet-jvb19\",project=\"vpsfree\"}",
     "legendFormat": "jvb19"
    },
    {
     "expr": "jitsi_participants{alias=\"meet-jvb20\",project=\"vpsfree\"}",
     "legendFormat": "jvb20"
    }
   ]
  },
  {
   "title": "Audio Channels",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jitsi_endpoints_sending_audio{alias=\"meet-jvb1\",project=\"vpsfree\"}",
     "legendFormat": "jvb1"
    },
    {
     "expr": "jitsi_endpoints_sending_audio{alias=\"meet-jvb2\",project=\"vpsfree\"}",
     "legendFormat": "jvb2"
    },
    {
     "expr": "jitsi_endpoints_sending_audio{alias=\"meet-jvb3\",project=\"vpsfree\"}",
     "legendFormat": "jvb3"
    },
    {
     "expr": "jitsi_endpoints_sending_audio{alias=\"meet-jvb4\",project=\"vpsfree\"}",
     "legendFormat": "jvb4"
    },
    {
     "expr": "jitsi_endpoints_sending_audio{alias=\"meet-jvb5\",project=\"vpsfree\"}",
     "legendFormat": "jvb5"
    },
    {
     "expr": "jitsi_endpoints_sending_audio{alias=\"meet-jvb6\",project=\"vpsfree\"}",
     "legendFormat": "jvb6"
    },
    {
     "expr": "jitsi_endpoints_sending_audio{alias=\"meet-jvb7\",project=\"vpsfree\"}",
     "legendFormat": "jvb7"
    },
    {
     "expr": "jitsi_endpoints_sending_audio{alias=\"meet-jvb8\",project=\"vpsfree\"}",
     "legendFormat": "jvb8"
    },
    {
     "expr": "jitsi_endpoints_sending_audio{alias=\"meet-jvb9\",project=\"vpsfree\"}",
     "legendFormat": "jvb9"
    },
    {
     "expr": "jitsi_endpoints_sending_audio{alias=\"meet-jvb10\",project=\"vpsfree\"}",
     "legendFormat": "jvb10"
    },
    {
     "expr": "jitsi_endpoints_sending_audio{alias=\"meet-jvb11\",project=\"vpsfree\"}",
     "legendFormat": "jvb11"
    },
    {
     "expr": "jitsi_endpoints_sending_audio{alias=\"meet-jvb12\",project=\"vpsfree\"}",
     "legendFormat": "jvb12"
    },
    {
     "expr": "jitsi_endpoints_sending_audio{alias=\"meet-jvb13\",project=\"vpsfree\"}",
     "legendFormat": "jvb13"
    },
    {
     "expr": "jitsi_endpoints_sending_audio{alias=\"meet-jvb14\",project=\"vpsfree\"}",
     "legendFormat": "jvb14"
    },
    {
     "expr": "jitsi_endpoints_sending_audio{alias=\"meet-jvb15\",project=\"vpsfree\"}",
     "legendFormat": "jvb15"
    },
    {
     "expr": "jitsi_endpoints_sending_audio{alias=\"meet-jvb16\",project=\"vpsfree\"}",
     "legendFormat": "jvb16"
    },
    {
     "expr": "jitsi_endpoints_sending_audio{alias=\"meet-jvb17\",project=\"vpsfree\"}",
     "legendFormat": "jvb17"
    },
    {
     "expr": "jitsi_endpoints_sending_audio{alias=\"meet-jvb18\",project=\"vpsfree\"}",
     "legendFormat": "jvb18"
    },
    {
     "expr": "jitsi_endpoints_sending_audio{alias=\"meet-jvb19\",project=\"vpsfree\"}",
     "legendFormat": "jvb19"
    },
    {
     "expr": "jitsi_endpoints_sending_audio{alias=\"meet-jvb20\",project=\"vpsfree\"}",
     "legendFormat": "jvb20"
    }
   ]
  },
  {
   "title": "Download Link Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "jitsi_bit_rate_download{alias=\"meet-jvb1\",project=\"vpsfree\"}",
     "legendFormat": "jvb1"
    },
    {
     "expr": "jitsi_bit_rate_download{alias=\"meet-jvb2\",project=\"vpsfree\"}",
     "legendFormat": "jvb2"
    },
    {
     "expr": "jitsi_bit_rate_download{alias=\"meet-jvb3\",project=\"vpsfree\"}",
     "legendFormat": "jvb3"
    },
    {
     "expr": "jitsi_bit_rate_download{alias=\"meet-jvb4\",project=\"vpsfree\"}",
     "legendFormat": "jvb4"
    },
    {
     "expr": "jitsi_bit_rate_download{alias=\"meet-jvb5\",project=\"vpsfree\"}",
     "legendFormat": "jvb5"
    },
    {
     "expr": "jitsi_bit_rate_download{alias=\"meet-jvb6\",project=\"vpsfree\"}",
     "legendFormat": "jvb6"
    },
    {
     "expr": "jitsi_bit_rate_download{alias=\"meet-jvb7\",project=\"vpsfree\"}",
     "legendFormat": "jvb7"
    },
    {
     "expr": "jitsi_bit_rate_download{alias=\"meet-jvb8\",project=\"vpsfree\"}",
     "legendFormat": "jvb8"
    },
    {
     "expr": "jitsi_bit_rate_download{alias=\"meet-jvb9\",project=\"vpsfree\"}",
     "legendFormat": "jvb9"
    },
    {
     "expr": "jitsi_bit_rate_download{alias=\"meet-jvb10\",project=\"vpsfree\"}",
     "legendFormat": "jvb10"
    },
    {
     "expr": "jitsi_bit_rate_download{alias=\"meet-jvb11\",project=\"vpsfree\"}",
     "legendFormat": "jvb11"
    },
    {
     "expr": "jitsi_bit_rate_download{alias=\"meet-jvb12\",project=\"vpsfree\"}",
     "legendFormat": "jvb12"
    },
    {
     "expr": "jitsi_bit_rate_download{alias=\"meet-jvb13\",project=\"vpsfree\"}",
     "legendFormat": "jvb13"
    },
    {
     "expr": "jitsi_bit_rate_download{alias=\"meet-jvb14\",project=\"vpsfree\"}",
     "legendFormat": "jvb14"
    },
    {
     "expr": "jitsi_bit_rate_download{alias=\"meet-jvb15\",project=\"vpsfree\"}",
     "legendFormat": "jvb15"
    },
    {
     "expr": "jitsi_bit_rate_download{alias=\"meet-jvb16\",project=\"vpsfree\"}",
     "legendFormat": "jvb16"
    },
    {
     "expr": "jitsi_bit_rate_download{alias=\"meet-jvb17\",project=\"vpsfree\"}",
     "legendFormat": "jvb17"
    },
    {
     "expr": "jitsi_bit_rate_download{alias=\"meet-jvb18\",project=\"vpsfree\"}",
     "legendFormat": "jvb18"
    },
    {
     "expr": "jitsi_bit_rate_download{alias=\"meet-jvb19\",project=\"vpsfree\"}",
     "legendFormat": "jvb19"
    },
    {
     "expr": "jitsi_bit_rate_download{alias=\"meet-jvb20\",project=\"vpsfree\"}",
     "legendFormat": "jvb20"
    }
   ]
  },
  {
   "title": "Upload Link Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "jitsi_bit_rate_upload{alias=\"meet-jvb1\",project=\"vpsfree\"}",
     "legendFormat": "jvb1"
    },
    {
     "expr": "jitsi_bit_rate_upload{alias=\"meet-jvb2\",project=\"vpsfree\"}",
     "legendFormat": "jvb2"
    },
    {
     "expr": "jitsi_bit_rate_upload{alias=\"meet-jvb3\",project=\"vpsfree\"}",
     "legendFormat": "jvb3"
    },
    {
     "expr": "jitsi_bit_rate_upload{alias=\"meet-jvb4\",project=\"vpsfree\"}",
     "legendFormat": "jvb4"
    },
    {
     "expr": "jitsi_bit_rate_upload{alias=\"meet-jvb5\",project=\"vpsfree\"}",
     "legendFormat": "jvb5"
    },
    {
     "expr": "jitsi_bit_rate_upload{alias=\"meet-jvb6\",project=\"vpsfree\"}",
     "legendFormat": "jvb6"
    },
    {
     "expr": "jitsi_bit_rate_upload{alias=\"meet-jvb7\",project=\"vpsfree\"}",
     "legendFormat": "jvb7"
    },
    {
     "expr": "jitsi_bit_rate_upload{alias=\"meet-jvb8\",project=\"vpsfree\"}",
     "legendFormat": "jvb8"
    },
    {
     "expr": "jitsi_bit_rate_upload{alias=\"meet-jvb9\",project=\"vpsfree\"}",
     "legendFormat": "jvb9"
    },
    {
     "expr": "jitsi_bit_rate_upload{alias=\"meet-jvb10\",project=\"vpsfree\"}",
     "legendFormat": "jvb10"
    },
    {
     "expr": "jitsi_bit_rate_upload{alias=\"meet-jvb11\",project=\"vpsfree\"}",
     "legendFormat": "jvb11"
    },
    {
     "expr": "jitsi_bit_rate_upload{alias=\"meet-jvb12\",project=\"vpsfree\"}",
     "legendFormat": "jvb12"
    },
    {
     "expr": "jitsi_bit_rate_upload{alias=\"meet-jvb13\",project=\"vpsfree\"}",
     "legendFormat": "jvb13"
    },
    {
     "expr": "jitsi_bit_rate_upload{alias=\"meet-jvb14\",project=\"vpsfree\"}",
     "legendFormat": "jvb14"
    },
    {
     "expr": "jitsi_bit_rate_upload{alias=\"meet-jvb15\",project=\"vpsfree\"}",
     "legendFormat": "jvb15"
    },
    {
     "expr": "jitsi_bit_rate_upload{alias=\"meet-jvb16\",project=\"vpsfree\"}",
     "legendFormat": "jvb16"
    },
    {
     "expr": "jitsi_bit_rate_upload{alias=\"meet-jvb17\",project=\"vpsfree\"}",
     "legendFormat": "jvb17"
    },
    {
     "expr": "jitsi_bit_rate_upload{alias=\"meet-jvb18\",project=\"vpsfree\"}",
     "legendFormat": "jvb18"
    },
    {
     "expr": "jitsi_bit_rate_upload{alias=\"meet-jvb19\",project=\"vpsfree\"}",
     "legendFormat": "jvb19"
    },
    {
     "expr": "jitsi_bit_rate_upload{alias=\"meet-jvb20\",project=\"vpsfree\"}",
     "legendFormat": "jvb20"
    }
   ]
  }
 ]
}