# This file is generated by confctl, changes will be lost
[
  ./jvb1/module.nix
  ./jvb10/module.nix
  ./jvb11/module.nix
  ./jvb2/module.nix
  ./jvb3/module.nix
  ./jvb4/module.nix
  ./jvb5/module.nix
  ./jvb6/module.nix
  ./jvb7/module.nix
  ./jvb8/module.nix
  ./jvb9/module.nix
  ./meet-nixos/module.nix
  ./test-jvb01/module.nix
  ./test-meet/module.nix
]
